Issue 1093 parameterize xsi schemalocation attribute
usnistgov/OSCAL pull request #1162
Opened 2022-03-08 21:35 UTC by aj-stein-nist

# Committer Notes

This PR implements a parameter in the RC2 to 1.0.0 content-upgrader script to specify the `xsi:schemaLocation` attribute in the top-level XML node for the given model of that OSCAL document instance when executing the content upgrade. The parameter is empty (`''` string) by default, will intentionally not insert the attribute to be backwards compatible. It will only insert the schema location if explicitly set when a developer overrides it or the XProc pipeline in CI/CD sets it.

This code implements and closes usnistgov/OSCAL#1093. 

### All Submissions:

- [ ] Have you selected the correct base branch per  [Contributing](https://github.com/usnistgov/OSCAL/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [ ] Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.

2022-03-08 22:29 UTC, aj-stein-nist commented
I am sorry about that, I just had a really weird experience with `git` and oXgen on my computer, and stashing and backing up that branch did not do me favors this time.

So, @wendellpiez helped work on this with me. I still have some open questions:

- Do I have to document the README to some degree about how to use this parameter? If so, would that be [in this README here](https://github.com/usnistgov/OSCAL/blob/75a3fc177a63c04d8719824cb88039c16bbd0d38/src/release/README.txt)?
- Do I need to help stub out tests around this new parameter and related functionality for these converters. If so, where should I do that and how?

2022-03-09 16:50 UTC, aj-stein-nist commented
OK, touched this up and rebased to `release-1.0` in place of `develop`. This is ready for review, pending feedback in the above comment about documentation and testing (the content upgraders do not have much in the way of docs and tests to begin with).

2022-03-09 17:07 UTC, david-waltermire-nist commented
This PR is missing instructions on how to use the new parameter. Please add this to the readme.

2022-03-09 17:07 UTC, david-waltermire-nist requested changes
Need instructions.

2022-03-09 17:09 UTC, aj-stein-nist commented
> Need instructions.

OK, I will add docs, but it seems we have none on the content-upgrade converters generally.

2022-03-10 16:37 UTC, aj-stein-nist commented
> Not only that, but the readme in the folder above is called `readme.txt` not `readme.md`, so it is not rendered for reading in Github. It may also be due for an update.

Excellent point. Yeah I was not even touching that one in particular because I thought it was a template for email notifications or something in the page. Should I overwrite it?

For now, I am working on a README.md in `.src/release/content-upgrade` because the instructions I am writing were/are topical to that. I assumed this original file served a purpose. I can also delete it or modify it, but was going to stay on task.

2022-03-10 17:14 UTC, aj-stein-nist commented
OK, README created, ready for re-review, @david-waltermire-nist and @wendellpiez.

2022-03-10 19:07 UTC, david-waltermire-nist commented
@aj-stein-nist Would you add a link to the upgrader readme page in src/release/readme.txt as part of this PR?

2022-03-10 21:01 UTC, aj-stein-nist commented
> @aj-stein-nist Would you add a link to the upgrader readme page in src/release/readme.txt as part of this PR?

Done. This is ready for re-review, @david-waltermire-nist.

2022-03-11 15:04 UTC, wendellpiez approved these changes
Most excellent thank you @aj-stein-nist!

2022-03-15 16:07 UTC, david-waltermire-nist approved these changes
This looks great. Thanks!

2022-03-15 16:07 UTC, merged