OSCAL Mini-workshop page update
usnistgov/OSCAL pull request #1346
Opened 2022-07-12 18:38 UTC by iMichaela

# Committer Notes

OSCAL Mini-workshop page was updated with Telos' speaker info.

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/usnistgov/OSCAL/blob/main/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers
](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [ ] Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.

2022-07-12 18:46 UTC, iMichaela commented
@david-waltermire-nist or @aj-stein-nist - Can you please review and accept the PR at your earliest convenience - the presentation is tomorrow?

2022-07-12 18:50 UTC, aj-stein-nist requested changes
I know it is a simple change, but we might want to fix this first or it will mess up page render. Otherwise, looks good.

2022-07-12 18:50 UTC, aj-stein-nist commented on docs/content/learn/presentations/mini-workshop/_index.md
> +>>>>>>> 833a646ce98188fc17d029723e5a34bc08c72e5f
We might need to fix this bit. I assume you want the more detailed one with more presenters, not just Matthew Donkin? There is merge conflict metadata in here still that will break the page.

```suggestion
|  2022/07/13 |  11:00AM-12:00PM EDT  | OSCAL Implementation: Early Lessons Learned | Matthew Donkin, Security Assurance Manager, AWS & Stephanie Lacy, Senior Solutions Architect, Telos| presentation | L2 |
```

2022-07-13 00:41 UTC, aj-stein-nist approved these changes

2022-07-13 18:38 UTC, david-waltermire-nist approved these changes

2022-07-13 18:38 UTC, merged