Added New Examples Page, Issue: #1294
usnistgov/OSCAL pull request #1675
Opened 2023-02-28 19:10 UTC by Arminta-Jenkins-NIST

# Committer Notes

We created a page similar to [OSCAL tools] (https://pages.nist.gov/OSCAL/tools/) that provides links to OSCAL content (catalogs, profiles, component-definitions, etc.) generated by NIST and website where community can contribute. 

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/usnistgov/OSCAL/blob/main/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers
](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [x] Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.

2023-02-28 19:56 UTC, aj-stein-nist requested changes
I would request a minor change, but other than that it looks good. Thanks so much to you and Michaela for working on this.

2023-02-28 19:56 UTC, aj-stein-nist commented on docs/content/examples/_index.md
> +{{% callout note %}} More OSCAL examples supporting the use of the OSCAL models are developed and maintained by the community in their [OSCAL Club](https://github.com/oscal-club/examples) repository.
A minor change if you will accept it before approval.

```suggestion
{{% callout note %}} More OSCAL examples supporting the use of the OSCAL models are developed and maintained by the community in the [OSCAL Club examples repository](https://github.com/oscal-club/examples) .{{% /callout %}}
```

2023-02-28 23:07 UTC, iMichaela submitted a review, later dismissed
I like AJ's suggestions. LGTM. We might want to also consider adding a link to the SP 800-53 catalogs and baselines on this page, but we can do it with a new PR if the team finds acceptable the proposal.

2023-03-01 19:35 UTC, aj-stein-nist approved these changes
LGTM, thanks to both of you.

2023-03-01 19:38 UTC, merged

2023-03-01 23:44 UTC, aj-stein-nist commented
> I like AJ's suggestions. LGTM. We might want to also consider adding a link to the SP 800-53 catalogs and baselines on this page, but we can do it with a new PR if the team finds acceptable the proposal.

I did not miss the feedback in this comment, I am creating an issue to follow on with that to prioritize at a later date. Then we can close out the related issue for this.