Added changes for #1798
usnistgov/OSCAL pull request #1842
Opened 2023-07-07 16:23 UTC by Arminta-Jenkins-NIST

# Committer Notes

Made security-sensitivity-level and security-impact-level optional attributes. Closes #1798. 

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/usnistgov/OSCAL/blob/main/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

(For reviewers: [The wiki has guidance](https://github.com/usnistgov/OSCAL/wiki/Issue-Review) on code review and overall issue review for completeness.)

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [ ] Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.

2023-07-07 19:26 UTC, GaryGapinski approved these changes
LGTM. Please inform FedRAMP that they must impose their (and that of anyone subject to FIPS 199) specific requirement for these FIPS 199/SP 800-60 attributes to be present.

2023-07-07 20:14 UTC, aj-stein-nist requested changes
@Arminta-Jenkins-NIST can you please review the checklist in the PR template and check it for us? Also, can you rebase this pull request on develop to surpress the CI/CD failure checking an outdated Markdown link:

```sh
git checkout 1798-optional-security-sensitivity-level # to be sure
git fetch upstream
git pull -r upstream develop
git push upstream HEAD -f
```

2023-07-07 21:37 UTC, aj-stein-nist commented
> @aj-stein-nist DONE Here is the result:
> 
> ```shell
> PS C:\Users\ajj2\git\OSCAL> git push upstream HEAD -f
> Everything up-to-date
> ```

Thanks for that update, please also review the checklist with the boxes in the pull request form to let us know what is or is not complete From the PR generated from the template, links to issue completeness guidelines.

https://github.com/usnistgov/OSCAL/wiki/Issue-Review#is-the-checklist-list-complete

Thanks!

2023-07-11 13:15 UTC, aj-stein-nist approved these changes

2023-07-11 13:19 UTC, merged